module

public import Noperthedron.SnubCube.CayleyGlobalCertificate
public meta import Noperthedron.SnubCube.CayleyGlobalCertificate

@[expose] public section


/-!
# Positive-radius polynomial Cayley global-certificate smoke test

Generated by `scripts/snub_certificate_search.py cayley-global-smoke`.  The
row spans all five Cayley-pose coordinates and is checked by both decision
paths before its semantic non-Rupert theorem is invoked.
-/

namespace Noperthedron.SnubCube.CayleyGlobalCertificateSmoke

def smokeInterval : CayleyInterval ℚ :=
  CayleyInterval.mk
    { θ := 59 / 200, φ := 219 / 200,
      x := 39 / 200, y := 19 / 200, z := -1 / 200 }
    { θ := 61 / 200, φ := 221 / 200,
      x := 41 / 200, y := 21 / 200, z := 1 / 200 }
    (by rw [CayleyPose.le_iff]; norm_num)

def smokeBox : CayleyGlobalCertificate.Box where
  interval := smokeInterval
  contact := ![
    { innerIndex := VertexIndex.ofFin24 1
      outerIndex := VertexIndex.ofFin24 13
      direction := ![43179 / 81821, -69500 / 81821] },
    { innerIndex := VertexIndex.ofFin24 5
      outerIndex := VertexIndex.ofFin24 15
      direction := ![2491 / 2509, 300 / 2509] },
    { innerIndex := VertexIndex.ofFin24 14
      outerIndex := VertexIndex.ofFin24 4
      direction := ![-999271 / 1000729, 54000 / 1000729] }
  ]

theorem smoke_valid_kernel : smokeBox.Valid := by
  decide +kernel

theorem smoke_valid_native : smokeBox.Valid := by
  native_decide

theorem smoke_excludes_translated_pose :
    ¬ ∃ p ∈ smokeInterval.toReal, ∃ offset : ℝ²,
      RupertPose (p.matrixPoseWithOffset offset)
        normalizedExactPolyhedron.hull :=
  smokeBox.valid_imp_no_translated_rupert_in_interval smoke_valid_kernel

end Noperthedron.SnubCube.CayleyGlobalCertificateSmoke

end
