module

public import Noperthedron.SnubCube.ProjectiveLocalCertificate
public meta import Noperthedron.SnubCube.ProjectiveLocalCertificate

@[expose] public section


/-!
# Projective local-rigidity certificate smoke test

This certificate was generated by `scripts/snub_certificate_search.py` at the
positive projective view `(3/5, 3/20, 1/4)`.  Its support contacts include
silhouette-edge endpoints, exercising the exact transition case in which a
support tie persists throughout the view triangle.  Both decision paths
check the same rational proposition.
-/

namespace Noperthedron.SnubCube.ProjectiveLocalCertificateSmoke

open ProjectiveView ProjectiveLocalCertificate

def smokeInterval : CayleyInterval ℚ :=
  CayleyInterval.mk
    { θ := 0, φ := 0, x := 0, y := 0, z := 0 }
    { θ := 0, φ := 0, x := 0, y := 0, z := 0 }
    (by rw [CayleyPose.le_iff]; norm_num)

def smokeTriangle : Triangle ℚ := ![
  ![60001 / 100000, 14999 / 100000, 1 / 4],
  ![3 / 5, 15001 / 100000, 24999 / 100000],
  ![59999 / 100000, 3 / 20, 25001 / 100000]]

def smokeCertificates : Fin 4 → AxisCertificate := ![
  { edgeStart := ![VertexIndex.ofFin24 13, VertexIndex.ofFin24 10,
        VertexIndex.ofFin24 14]
    edgeFinish := ![VertexIndex.ofFin24 5, VertexIndex.ofFin24 14,
        VertexIndex.ofFin24 4]
    supportIndex := ![VertexIndex.ofFin24 5, VertexIndex.ofFin24 14,
        VertexIndex.ofFin24 14]
    nonzeroWitness := ![VertexIndex.ofFin24 14, VertexIndex.ofFin24 13,
        VertexIndex.ofFin24 5]
    B := 494583207 / 1000000000 },
  { edgeStart := ![VertexIndex.ofFin24 5, VertexIndex.ofFin24 15,
        VertexIndex.ofFin24 4]
    edgeFinish := ![VertexIndex.ofFin24 15, VertexIndex.ofFin24 3,
        VertexIndex.ofFin24 8]
    supportIndex := ![VertexIndex.ofFin24 15, VertexIndex.ofFin24 15,
        VertexIndex.ofFin24 8]
    nonzeroWitness := ![VertexIndex.ofFin24 4, VertexIndex.ofFin24 8,
        VertexIndex.ofFin24 15]
    B := 241217891 / 500000000 },
  { edgeStart := ![VertexIndex.ofFin24 3, VertexIndex.ofFin24 14,
        VertexIndex.ofFin24 1]
    edgeFinish := ![VertexIndex.ofFin24 10, VertexIndex.ofFin24 4,
        VertexIndex.ofFin24 13]
    supportIndex := ![VertexIndex.ofFin24 3, VertexIndex.ofFin24 4,
        VertexIndex.ofFin24 13]
    nonzeroWitness := ![VertexIndex.ofFin24 1, VertexIndex.ofFin24 5,
        VertexIndex.ofFin24 10]
    B := 1074624887 / 1000000000 },
  { edgeStart := ![VertexIndex.ofFin24 3, VertexIndex.ofFin24 4,
        VertexIndex.ofFin24 1]
    edgeFinish := ![VertexIndex.ofFin24 10, VertexIndex.ofFin24 8,
        VertexIndex.ofFin24 13]
    supportIndex := ![VertexIndex.ofFin24 3, VertexIndex.ofFin24 4,
        VertexIndex.ofFin24 1]
    nonzeroWitness := ![VertexIndex.ofFin24 1, VertexIndex.ofFin24 15,
        VertexIndex.ofFin24 10]
    B := 973031233 / 1000000000 }]

def smokeBox : Box where
  interval := smokeInterval
  triangle := smokeTriangle
  certificate := smokeCertificates
  c := 300709 / 50000000
  δ := 179 / 25000000

theorem smoke_valid_kernel : smokeBox.Valid := by
  decide +kernel

theorem smoke_valid_native : smokeBox.Valid := by
  native_decide

theorem smoke_no_translated_rupert :
    ¬ ∃ p ∈ smokeInterval.toReal, ∃ offset : ℝ²,
      (p.matrixPoseWithOffset offset).InOuterViewChamber ∧
      InTriangle (toReal smokeTriangle) (normalizedView p) ∧
      RupertPose (p.matrixPoseWithOffset offset)
        normalizedExactPolyhedron.hull := by
  rintro ⟨p, hp, offset, hchamber, htriangle, hrupert⟩
  exact smokeBox.valid_imp_not_translated_rupert smoke_valid_kernel
    p hp offset hchamber htriangle hrupert

/-! A degenerate triangle on the symmetry wall exercises exact algebraic
support ties whose selected vertex is not an endpoint of the stored edge. -/

def boundaryTriangle : Triangle ℚ := ![
  ![4 / 5, 1 / 5, 0], ![4 / 5, 1 / 5, 0], ![4 / 5, 1 / 5, 0]]

def boundaryCertificates : Fin 4 → AxisCertificate := ![
  { edgeStart := ![VertexIndex.ofFin24 8, VertexIndex.ofFin24 15,
        VertexIndex.ofFin24 10]
    edgeFinish := ![VertexIndex.ofFin24 9, VertexIndex.ofFin24 11,
        VertexIndex.ofFin24 14]
    supportIndex := ![VertexIndex.ofFin24 1, VertexIndex.ofFin24 11,
        VertexIndex.ofFin24 10]
    nonzeroWitness := ![VertexIndex.ofFin24 2, VertexIndex.ofFin24 8,
        VertexIndex.ofFin24 9]
    B := 307367627 / 250000000 },
  { edgeStart := ![VertexIndex.ofFin24 8, VertexIndex.ofFin24 15,
        VertexIndex.ofFin24 10]
    edgeFinish := ![VertexIndex.ofFin24 9, VertexIndex.ofFin24 11,
        VertexIndex.ofFin24 14]
    supportIndex := ![VertexIndex.ofFin24 0, VertexIndex.ofFin24 11,
        VertexIndex.ofFin24 10]
    nonzeroWitness := ![VertexIndex.ofFin24 2, VertexIndex.ofFin24 8,
        VertexIndex.ofFin24 9]
    B := 307367627 / 250000000 },
  { edgeStart := ![VertexIndex.ofFin24 5, VertexIndex.ofFin24 15,
        VertexIndex.ofFin24 4]
    edgeFinish := ![VertexIndex.ofFin24 15, VertexIndex.ofFin24 11,
        VertexIndex.ofFin24 8]
    supportIndex := ![VertexIndex.ofFin24 5, VertexIndex.ofFin24 15,
        VertexIndex.ofFin24 4]
    nonzeroWitness := ![VertexIndex.ofFin24 4, VertexIndex.ofFin24 8,
        VertexIndex.ofFin24 15]
    B := 387860023 / 500000000 },
  { edgeStart := ![VertexIndex.ofFin24 14, VertexIndex.ofFin24 9,
        VertexIndex.ofFin24 10]
    edgeFinish := ![VertexIndex.ofFin24 4, VertexIndex.ofFin24 5,
        VertexIndex.ofFin24 14]
    supportIndex := ![VertexIndex.ofFin24 4, VertexIndex.ofFin24 5,
        VertexIndex.ofFin24 14]
    nonzeroWitness := ![VertexIndex.ofFin24 5, VertexIndex.ofFin24 14,
        VertexIndex.ofFin24 9]
    B := 387860023 / 500000000 }]

def boundaryBox : Box where
  interval := smokeInterval
  triangle := boundaryTriangle
  certificate := boundaryCertificates
  c := 2628893 / 200000000
  δ := 59 / 1000000000

theorem boundary_valid_kernel : boundaryBox.Valid := by
  decide +kernel

theorem boundary_valid_native : boundaryBox.Valid := by
  native_decide

end Noperthedron.SnubCube.ProjectiveLocalCertificateSmoke

end
