module

public import Noperthedron.BalancedSupport.Transition
public import Noperthedron.SnubCube.TribonacciPolynomial

@[expose] public section


/-!
# Blown-up projective transition certificates

At the hard snub-cube silhouette seam, write `d` for the exact linear seam
equation and put the relative z-Cayley coordinate in the form `z = d*t`.
For the balanced certificate with outer edges

`(14,4), (8,9), (5,15)`

and selected inner vertices `14,1,15`, the denominator-cleared obstruction
is `d² * zAxisQuotient(d,t)`.  The five coefficients below were generated by
`scripts/snub_certificate_search.py` using exact arithmetic in the same
cubic quotient ring as `ExactArithmetic.lean`.
-/

namespace Noperthedron.SnubCube.ProjectiveTransitionCertificate

open Noperthedron.Checker
open TribonacciExpr TribonacciPolynomial

def qLinear : TribonacciExpr :=
  ⟨12 / 25, 16 / 25, 12 / 25⟩

def qSquare : TribonacciExpr :=
  ⟨-24 / 625, -48 / 625, -56 / 625⟩

def qDLinear : TribonacciExpr :=
  ⟨0, -4, 0⟩

def qDSquare : TribonacciExpr :=
  ⟨4 / 25, 0, 4 / 5⟩

def qDDSquare : TribonacciExpr :=
  ⟨-4, 0, 0⟩

/-- The exact quotient after removing the structural factor `d²`, written
in Horner form to keep interval dependency small. -/
def zAxisQuotient : Polynomial 2 :=
  let d : Polynomial 2 := .var 0
  let t : Polynomial 2 := .var 1
  t * (.const qLinear + d * .const qDLinear +
    t * (.const qSquare + d * .const qDSquare +
      d * d * .const qDDSquare))

/-! ## Exact expansion and structural factorization -/

abbrev PolyVector := Fin 3 → Polynomial 2
abbrev ExactVector := Fin 3 → TribonacciExpr

def vi (index : Fin 24) : VertexIndex := VertexIndex.ofFin24 index

def exactEdge (start finish : Fin 24) : ExactVector :=
  symbolicVertexDifference (vi start) (vi finish)

def exactSelectedVertex (index : Fin 24) : ExactVector :=
  normalizedSymbolicVertex (vi index)

def dotPolyExact (left : PolyVector) (right : ExactVector) : Polynomial 2 :=
  left 0 * .const (right 0) + left 1 * .const (right 1) +
    left 2 * .const (right 2)

def dotPoly (left right : PolyVector) : Polynomial 2 :=
  left 0 * right 0 + left 1 * right 1 + left 2 * right 2

def crossExactPoly (left : ExactVector) (right : PolyVector) : PolyVector := ![
  .const (left 1) * right 2 - .const (left 2) * right 1,
  .const (left 2) * right 0 - .const (left 0) * right 2,
  .const (left 0) * right 1 - .const (left 1) * right 0]

def seamU : TribonacciExpr := ⟨1, 1 / 2, -1 / 2⟩
def inverseSeamSlope : TribonacciExpr := ⟨25 / 4, -25 / 2, 25 / 4⟩

def viewPolynomial : PolyVector :=
  let d : Polynomial 2 := .var 0
  let u : Polynomial 2 := .const seamU + .const inverseSeamSlope * d
  ![1 - u, u, 0]

def edgeStart : Fin 3 → Fin 24 := ![14, 8, 5]
def edgeFinish : Fin 3 → Fin 24 := ![4, 9, 15]
def selectedVertex : Fin 3 → Fin 24 := ![14, 1, 15]

def edgeData : Fin 3 → ExactVector := ![
  ![⟨1 / 5, -1 / 5, 0⟩, 0, ⟨1 / 5, 1 / 5, 0⟩],
  ![⟨2 / 5, 0, 0⟩, ⟨0, -2 / 5, 0⟩, 0],
  ![⟨1 / 5, -1 / 5, 0⟩, 0, ⟨-1 / 5, -1 / 5, 0⟩]]

def selectedData : Fin 3 → ExactVector := ![
  ![⟨1 / 5, 0, 0⟩, ⟨0, 0, -1 / 5⟩, ⟨0, 1 / 5, 0⟩],
  ![⟨0, 1 / 5, 0⟩, ⟨1 / 5, 0, 0⟩, ⟨0, 0, -1 / 5⟩],
  ![⟨-1 / 5, 0, 0⟩, ⟨0, 0, 1 / 5⟩, ⟨0, 1 / 5, 0⟩]]

/-- The compact generated data is exactly the indexed snub-cube geometry. -/
theorem edgeData_exact (i : Fin 3) :
    edgeData i = exactEdge (edgeStart i) (edgeFinish i) := by
  fin_cases i <;> decide +kernel

theorem selectedData_exact (i : Fin 3) :
    selectedData i = exactSelectedVertex (selectedVertex i) := by
  fin_cases i <;> decide +kernel

def edge (i : Fin 3) : ExactVector := edgeData i

def weightPolynomial : Fin 3 → Polynomial 2 := ![
  dotPolyExact viewPolynomial (symbolicCross (edge 1) (edge 2)),
  dotPolyExact viewPolynomial (symbolicCross (edge 2) (edge 0)),
  dotPolyExact viewPolynomial (symbolicCross (edge 0) (edge 1))]

/-- `N(0,0,d*t)q - (1+(d*t)²)q` for one exact selected vertex. -/
def displacementPolynomial (i : Fin 3) : PolyVector :=
  let d : Polynomial 2 := .var 0
  let t : Polynomial 2 := .var 1
  let z := d * t
  let zSq := z * z
  let q := selectedData i
  ![.const (ofRat (-2) * q 0) * zSq + .const (ofRat (-2) * q 1) * z,
    .const (ofRat 2 * q 0) * z + .const (ofRat (-2) * q 1) * zSq,
    0]

def contactPolynomial (i : Fin 3) : PolyVector :=
  crossExactPoly (edge i) (displacementPolynomial i)

/-- The complete denominator-cleared weighted displacement before the
`d²` factor is removed. -/
def zAxisExpanded : Polynomial 2 :=
  weightPolynomial 0 * dotPoly viewPolynomial (contactPolynomial 0) +
  weightPolynomial 1 * dotPoly viewPolynomial (contactPolynomial 1) +
  weightPolynomial 2 * dotPoly viewPolynomial (contactPolynomial 2)

def weightBase : TribonacciExpr := ⟨2 / 25, 4 / 25, 0⟩
def weightSlope : TribonacciExpr := ⟨1, -1, 0⟩
def contactLinear : TribonacciExpr := ⟨1, 0, 1⟩
def contactSquare : TribonacciExpr := ⟨-2 / 25, -4 / 25, -2 / 25⟩
def contactDSquare : TribonacciExpr := ⟨-1, 0, 1⟩

theorem eval_weight_zero (d t : ℝ) :
    evalReal ![d, t] (weightPolynomial 0) =
      weightBase.eval + d * weightSlope.eval := by
  simp [weightPolynomial, dotPolyExact, viewPolynomial, edge, edgeData,
    seamU, inverseSeamSlope, weightBase, weightSlope,
    TribonacciExpr.eval, symbolicCross]
  ring_nf
  rw [tribonacci_fourth, tribonacci_cubic]
  ring

theorem eval_weight_two (d t : ℝ) :
    evalReal ![d, t] (weightPolynomial 2) =
      weightBase.eval + d * weightSlope.eval := by
  simp [weightPolynomial, dotPolyExact, viewPolynomial, edge, edgeData,
    seamU, inverseSeamSlope, weightBase, weightSlope,
    TribonacciExpr.eval, symbolicCross]
  ring_nf
  rw [tribonacci_fourth, tribonacci_cubic]
  ring

theorem eval_contact_zero (d t : ℝ) :
    evalReal ![d, t] (dotPoly viewPolynomial (contactPolynomial 0)) =
      d ^ 2 * t * contactLinear.eval +
        d ^ 2 * t ^ 2 * contactSquare.eval +
        d ^ 3 * t ^ 2 * contactDSquare.eval := by
  simp [contactPolynomial, displacementPolynomial, dotPoly,
    crossExactPoly, viewPolynomial, edge, edgeData, selectedData,
    seamU, inverseSeamSlope, contactLinear, contactSquare,
    contactDSquare, TribonacciExpr.eval]
  ring_nf
  rw [tribonacci_fifth, tribonacci_fourth, tribonacci_cubic]
  ring

theorem eval_contact_one (d t : ℝ) :
    evalReal ![d, t] (dotPoly viewPolynomial (contactPolynomial 1)) = 0 := by
  simp [contactPolynomial, displacementPolynomial, dotPoly,
    crossExactPoly, viewPolynomial, edge, edgeData, selectedData,
    seamU, inverseSeamSlope, TribonacciExpr.eval]

theorem eval_contact_two (d t : ℝ) :
    evalReal ![d, t] (dotPoly viewPolynomial (contactPolynomial 2)) =
      d ^ 2 * t * contactLinear.eval +
        d ^ 2 * t ^ 2 * contactSquare.eval +
        d ^ 3 * t ^ 2 * contactDSquare.eval := by
  simp [contactPolynomial, displacementPolynomial, dotPoly,
    crossExactPoly, viewPolynomial, edge, edgeData, selectedData,
    seamU, inverseSeamSlope, contactLinear, contactSquare,
    contactDSquare, TribonacciExpr.eval]
  ring_nf
  rw [tribonacci_fifth, tribonacci_fourth, tribonacci_cubic]
  ring

theorem quotient_coefficient_linear :
    ofRat 2 * weightBase * contactLinear = qLinear := by decide +kernel

theorem quotient_coefficient_square :
    ofRat 2 * weightBase * contactSquare = qSquare := by decide +kernel

theorem quotient_coefficient_dLinear :
    ofRat 2 * weightSlope * contactLinear = qDLinear := by decide +kernel

theorem quotient_coefficient_dSquare :
    ofRat 2 * (weightBase * contactDSquare + weightSlope * contactSquare) =
      qDSquare := by decide +kernel

theorem quotient_coefficient_ddSquare :
    ofRat 2 * weightSlope * contactDSquare = qDDSquare := by decide +kernel

/-- Kernel-checked algebraic identity behind the generated quotient. -/
theorem eval_zAxisExpanded_factor (d t : ℝ) :
    evalReal ![d, t] zAxisExpanded =
      d ^ 2 * evalReal ![d, t] zAxisQuotient := by
  simp only [zAxisExpanded, evalReal_add, evalReal_mul,
    eval_weight_zero, eval_weight_two, eval_contact_zero,
    eval_contact_one, eval_contact_two, mul_zero, add_zero]
  have hlinear : 2 * weightBase.eval * contactLinear.eval = qLinear.eval := by
    simpa only [eval_mul, eval_ofRat, Rat.cast_ofNat] using
      congrArg TribonacciExpr.eval quotient_coefficient_linear
  have hsquare : 2 * weightBase.eval * contactSquare.eval = qSquare.eval := by
    simpa only [eval_mul, eval_ofRat, Rat.cast_ofNat] using
      congrArg TribonacciExpr.eval quotient_coefficient_square
  have hdlinear : 2 * weightSlope.eval * contactLinear.eval = qDLinear.eval := by
    simpa only [eval_mul, eval_ofRat, Rat.cast_ofNat] using
      congrArg TribonacciExpr.eval quotient_coefficient_dLinear
  have hdsquare :
      2 * (weightBase.eval * contactDSquare.eval +
        weightSlope.eval * contactSquare.eval) = qDSquare.eval := by
    simpa only [eval_mul, eval_add, eval_ofRat, Rat.cast_ofNat] using
      congrArg TribonacciExpr.eval quotient_coefficient_dSquare
  have hddsquare :
      2 * weightSlope.eval * contactDSquare.eval = qDDSquare.eval := by
    simpa only [eval_mul, eval_ofRat, Rat.cast_ofNat] using
      congrArg TribonacciExpr.eval quotient_coefficient_ddSquare
  simp [zAxisQuotient]
  rw [← hlinear, ← hsquare, ← hdlinear, ← hdsquare, ← hddsquare]
  ring

structure ZAxisBox where
  seam : RatBall
  ratio : RatBall
deriving DecidableEq, Repr

def ZAxisBox.variableBalls (box : ZAxisBox) : Fin 2 → RatBall :=
  ![box.seam, box.ratio]

def ZAxisBox.quotientBall (box : ZAxisBox) : RatBall :=
  evalBall box.variableBalls zAxisQuotient

@[mk_iff]
structure ZAxisBox.Valid (box : ZAxisBox) : Prop where
  seam_positive : 0 < box.seam.center - box.seam.radius
  ratio_positive : 0 < box.ratio.center - box.ratio.radius
  quotient_positive :
    0 < box.quotientBall.center - box.quotientBall.radius

instance (box : ZAxisBox) : Decidable box.Valid :=
  decidable_of_iff _ (ZAxisBox.valid_iff box).symm

theorem ZAxisBox.quotient_pos (box : ZAxisBox) (h : box.Valid)
    {d t : ℝ} (hd : box.seam.Holds d) (ht : box.ratio.Holds t) :
    0 < evalReal ![d, t] zAxisQuotient := by
  apply evalReal_pos_of_lower_pos _ zAxisQuotient h.quotient_positive
  intro i
  fin_cases i
  · exact hd
  · exact ht

/-- The factored obstruction is nonnegative throughout a valid blown-up
box, including the seam itself. -/
theorem ZAxisBox.factored_obstruction_nonnegative (box : ZAxisBox)
    (h : box.Valid) {d t : ℝ} (hd : box.seam.Holds d)
    (ht : box.ratio.Holds t) :
    0 ≤ d ^ 2 * evalReal ![d, t] zAxisQuotient := by
  exact mul_nonneg (sq_nonneg d) (box.quotient_pos h hd ht).le

end Noperthedron.SnubCube.ProjectiveTransitionCertificate

end
