"""Balanced-support experiments for Tom 7's Nopert #214.

The linked STL has twenty vertices in four fivefold orbits.  We interpret it
as the exact mathematical polyhedron generated by rotating four published
decimal seed vertices through multiples of 2*pi/5.  The decimal seeds are
exact rationals in the Lean model; floating point is used here only for
certificate discovery.

For a fixed pair of projected orientations, translation containment is a
two-variable linear feasibility problem.  Its minimal Farkas obstructions
use three outer edge normals whose nonnegative weighted sum is zero.  This
script enumerates those triples and reports the strongest normalized
balanced-support obstruction.
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import math
import random
from fractions import Fraction as Q


SEEDS_Q = (
    (Q("0.5542570167628148"), Q("0.13498214234883502"),
     Q("0.5670539264866502")),
    (Q("0.839503072954794"), Q("0.4526456900329921"),
     Q("0.3005768949769993")),
    (Q("0.7619849874129984"), Q("0.5429603653859462"),
     Q("-0.04074876955046458")),
    (Q("0.591853727475924"), Q("0.13110932665305655"),
     Q("-0.7653829489805983")),
)


# The exact target: the twenty distinct decimal vertices in the linked STL,
# ordered as five near-72-degree copies of the four seeds above.  Keeping the
# published decimals themselves makes the theorem's object unambiguous; the
# fivefold description is provenance and a useful numerical near-symmetry,
# not an equality silently imposed on the data.
VERTICES_Q = (
    SEEDS_Q[0], SEEDS_Q[1], SEEDS_Q[2], SEEDS_Q[3],
    (Q("0.04289919136693016"), Q("0.5688415234175154"), Q("0.5670539264866502")),
    (Q("-0.17107091670577093"), Q("0.9382900786342319"), Q("0.3005768949769993")),
    (Q("-0.2809196830211049"), Q("0.8924747677745009"), Q("-0.04074876955046458")),
    (Q("0.05820048051375984"), Q("0.6034013542664042"), Q("-0.7653829489805983")),
    (Q("-0.5277438584081657"), Q("0.2165812533354586"), Q("0.5670539264866502")),
    (Q("-0.9452307139655625"), Q("0.1272494698697746"), Q("0.3005768949769993")),
    (Q("-0.9356028996288878"), Q("0.008619375200364626"), Q("-0.04074876955046458")),
    (Q("-0.5558838523568445"), Q("0.2418132191412975"), Q("-0.7653829489805983")),
    (Q("-0.36906283321718863"), Q("-0.4349869475301504"), Q("0.5670539264866502")),
    (Q("-0.41311379173527674"), Q("-0.8596455812043055"), Q("0.3005768949769993")),
    (Q("-0.2973147089225043"), Q("-0.8871477009388876"), Q("-0.04074876955046458")),
    (Q("-0.40175559506751807"), Q("-0.45395256590805566"), Q("-0.7653829489805983")),
    (Q("0.29965048349560947"), Q("-0.4854179715716587"), Q("0.5670539264866502")),
    (Q("0.6899123494518161"), Q("-0.6585396573326932"), Q("0.3005768949769993")),
    (Q("0.7518523041594987"), Q("-0.5569068074219243"), Q("-0.04074876955046458")),
    (Q("0.3075852394346786"), Q("-0.5223713341527026"), Q("-0.7653829489805983")),
)


def vertices_float():
    return [tuple(map(float, vertex)) for vertex in VERTICES_Q]


VERTICES = vertices_float()

PUBLISHED_STL_SHA256 = (
    "847f2f999075f114030306631eff192d7350475fcce66a4e9fa0a77fc5ad7bb9"
)


def audit_stl(path):
    payload = open(path, "rb").read()
    vertices = set()
    for line in payload.decode("ascii").splitlines():
        fields = line.split()
        if fields[:1] == ["vertex"]:
            if len(fields) != 4:
                raise ValueError(f"malformed vertex line: {line!r}")
            vertices.add(tuple(Q(value) for value in fields[1:]))
    expected = set(VERTICES_Q)
    return {
        "sha256": hashlib.sha256(payload).hexdigest(),
        "sha256_matches_published":
            hashlib.sha256(payload).hexdigest() == PUBLISHED_STL_SHA256,
        "distinct_vertices": len(vertices),
        "expected_vertices": len(expected),
        "vertices_match": vertices == expected,
        "missing": [list(map(str, vertex)) for vertex in expected - vertices],
        "unexpected": [list(map(str, vertex)) for vertex in vertices - expected],
    }


def rot_m(theta, phi, vertex):
    x, y, z = vertex
    st, ct = math.sin(theta), math.cos(theta)
    sp, cp = math.sin(phi), math.cos(phi)
    return (-st * x + ct * y,
            -ct * cp * x - st * cp * y + sp * z)


def rot_r(alpha, point):
    x, y = point
    s, c = math.sin(alpha), math.cos(alpha)
    return (c * x - s * y, s * x + c * y)


def cross(left, right):
    return left[0] * right[1] - left[1] * right[0]


def dot(left, right):
    return left[0] * right[0] + left[1] * right[1]


def convex_hull(points):
    """Indices of the counterclockwise strict convex hull."""
    ordered = sorted(range(len(points)), key=lambda i: points[i])

    def half(indices):
        answer = []
        for index in indices:
            while len(answer) >= 2:
                a, b = points[answer[-2]], points[answer[-1]]
                ab = (b[0] - a[0], b[1] - a[1])
                bp = (points[index][0] - b[0], points[index][1] - b[1])
                if cross(ab, bp) > 1e-14:
                    break
                answer.pop()
            answer.append(index)
        return answer

    lower = half(ordered)
    upper = half(reversed(ordered))
    return lower[:-1] + upper[:-1]


def balanced_certificate(pose):
    theta1, phi1, theta2, phi2, alpha = pose
    inner = [rot_r(alpha, rot_m(theta1, phi1, vertex))
             for vertex in VERTICES]
    outer = [rot_m(theta2, phi2, vertex) for vertex in VERTICES]
    cycle = convex_hull(outer)
    contacts = []
    for position, start in enumerate(cycle):
        finish = cycle[(position + 1) % len(cycle)]
        edge = (outer[finish][0] - outer[start][0],
                outer[finish][1] - outer[start][1])
        norm = math.hypot(*edge)
        normal = (edge[1] / norm, -edge[0] / norm)
        outer_support = dot(normal, outer[start])
        inner_index = max(range(len(inner)),
                          key=lambda i: dot(normal, inner[i]))
        displacement = dot(normal, inner[inner_index]) - outer_support
        contacts.append((normal, displacement, inner_index, start, finish))

    best = None
    for indices in itertools.combinations(range(len(contacts)), 3):
        normals = [contacts[i][0] for i in indices]
        weights = [cross(normals[1], normals[2]),
                   cross(normals[2], normals[0]),
                   cross(normals[0], normals[1])]
        if all(weight <= 1e-14 for weight in weights):
            weights = [-weight for weight in weights]
        if not all(weight >= -1e-14 for weight in weights):
            continue
        total = sum(weights)
        if total <= 1e-14:
            continue
        weights = [max(weight, 0.0) / total for weight in weights]
        obstruction = sum(weights[j] * contacts[index][1]
                          for j, index in enumerate(indices))
        if best is None or obstruction > best[0]:
            best = (obstruction, indices, weights)

    if best is None:
        raise RuntimeError("outer silhouette has no balanced edge triple")
    obstruction, indices, weights = best
    return {
        "obstruction": obstruction,
        "outer_hull_size": len(cycle),
        "weights": weights,
        "contacts": [{
            "normal": contacts[index][0],
            "inner": contacts[index][2],
            "outer_start": contacts[index][3],
            "outer_finish": contacts[index][4],
            "displacement": contacts[index][1],
        } for index in indices],
    }


def random_profile(samples, seed):
    rng = random.Random(seed)
    minimum = None
    negative = 0
    hull_histogram = {}
    for _ in range(samples):
        pose = (rng.uniform(-math.pi, math.pi),
                rng.uniform(0.0, math.pi),
                rng.uniform(-math.pi, math.pi),
                rng.uniform(0.0, math.pi),
                rng.uniform(-math.pi, math.pi))
        certificate = balanced_certificate(pose)
        hull_size = certificate["outer_hull_size"]
        hull_histogram[hull_size] = hull_histogram.get(hull_size, 0) + 1
        if certificate["obstruction"] < 0:
            negative += 1
        if minimum is None or certificate["obstruction"] < minimum[0]:
            minimum = (certificate["obstruction"], pose, certificate)
    return {
        "samples": samples,
        "negative_obstructions": negative,
        "minimum_obstruction": minimum[0],
        "minimum_pose": minimum[1],
        "minimum_certificate": minimum[2],
        "outer_hull_histogram": hull_histogram,
    }


def main():
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="command", required=True)
    profile = sub.add_parser("profile")
    profile.add_argument("--samples", type=int, default=10000)
    profile.add_argument("--seed", type=int, default=1)
    pose = sub.add_parser("pose")
    pose.add_argument("values", help="theta1,phi1,theta2,phi2,alpha")
    audit = sub.add_parser("audit-stl")
    audit.add_argument("path")
    args = parser.parse_args()
    if args.command == "profile":
        print(json.dumps(random_profile(args.samples, args.seed), indent=2))
    elif args.command == "pose":
        values = tuple(map(float, args.values.split(",")))
        if len(values) != 5:
            parser.error("pose requires five comma-separated values")
        print(json.dumps(balanced_certificate(values), indent=2))
    else:
        print(json.dumps(audit_stl(args.path), indent=2))


if __name__ == "__main__":
    main()
