"""Balanced-support experiments for Tom 7's Nopert #214.

The linked STL has twenty vertices in four fivefold orbits.  We interpret it
as the exact mathematical polyhedron generated by rotating four published
decimal seed vertices through multiples of 2*pi/5.  The decimal seeds are
exact rationals in the Lean model; floating point is used here only for
certificate discovery.

For a fixed pair of projected orientations, translation containment is a
two-variable linear feasibility problem.  Its minimal Farkas obstructions
use three outer edge normals whose nonnegative weighted sum is zero.  This
script enumerates those triples and reports the strongest normalized
balanced-support obstruction.
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import math
import random
from fractions import Fraction as Q


SEEDS_Q = (
    (Q("0.5542570167628148"), Q("0.13498214234883502"),
     Q("0.5670539264866502")),
    (Q("0.839503072954794"), Q("0.4526456900329921"),
     Q("0.3005768949769993")),
    (Q("0.7619849874129984"), Q("0.5429603653859462"),
     Q("-0.04074876955046458")),
    (Q("0.591853727475924"), Q("0.13110932665305655"),
     Q("-0.7653829489805983")),
)


# The exact target: the twenty distinct decimal vertices in the linked STL,
# ordered as five near-72-degree copies of the four seeds above.  Keeping the
# published decimals themselves makes the theorem's object unambiguous; the
# fivefold description is provenance and a useful numerical near-symmetry,
# not an equality silently imposed on the data.
VERTICES_Q = (
    SEEDS_Q[0], SEEDS_Q[1], SEEDS_Q[2], SEEDS_Q[3],
    (Q("0.04289919136693016"), Q("0.5688415234175154"), Q("0.5670539264866502")),
    (Q("-0.17107091670577093"), Q("0.9382900786342319"), Q("0.3005768949769993")),
    (Q("-0.2809196830211049"), Q("0.8924747677745009"), Q("-0.04074876955046458")),
    (Q("0.05820048051375984"), Q("0.6034013542664042"), Q("-0.7653829489805983")),
    (Q("-0.5277438584081657"), Q("0.2165812533354586"), Q("0.5670539264866502")),
    (Q("-0.9452307139655625"), Q("0.1272494698697746"), Q("0.3005768949769993")),
    (Q("-0.9356028996288878"), Q("0.008619375200364626"), Q("-0.04074876955046458")),
    (Q("-0.5558838523568445"), Q("0.2418132191412975"), Q("-0.7653829489805983")),
    (Q("-0.36906283321718863"), Q("-0.4349869475301504"), Q("0.5670539264866502")),
    (Q("-0.41311379173527674"), Q("-0.8596455812043055"), Q("0.3005768949769993")),
    (Q("-0.2973147089225043"), Q("-0.8871477009388876"), Q("-0.04074876955046458")),
    (Q("-0.40175559506751807"), Q("-0.45395256590805566"), Q("-0.7653829489805983")),
    (Q("0.29965048349560947"), Q("-0.4854179715716587"), Q("0.5670539264866502")),
    (Q("0.6899123494518161"), Q("-0.6585396573326932"), Q("0.3005768949769993")),
    (Q("0.7518523041594987"), Q("-0.5569068074219243"), Q("-0.04074876955046458")),
    (Q("0.3075852394346786"), Q("-0.5223713341527026"), Q("-0.7653829489805983")),
)


def vertices_float():
    return [tuple(map(float, vertex)) for vertex in VERTICES_Q]


VERTICES = vertices_float()

PUBLISHED_STL_SHA256 = (
    "847f2f999075f114030306631eff192d7350475fcce66a4e9fa0a77fc5ad7bb9"
)


def audit_stl(path):
    payload = open(path, "rb").read()
    vertices = set()
    for line in payload.decode("ascii").splitlines():
        fields = line.split()
        if fields[:1] == ["vertex"]:
            if len(fields) != 4:
                raise ValueError(f"malformed vertex line: {line!r}")
            vertices.add(tuple(Q(value) for value in fields[1:]))
    expected = set(VERTICES_Q)
    return {
        "sha256": hashlib.sha256(payload).hexdigest(),
        "sha256_matches_published":
            hashlib.sha256(payload).hexdigest() == PUBLISHED_STL_SHA256,
        "distinct_vertices": len(vertices),
        "expected_vertices": len(expected),
        "vertices_match": vertices == expected,
        "missing": [list(map(str, vertex)) for vertex in expected - vertices],
        "unexpected": [list(map(str, vertex)) for vertex in vertices - expected],
    }


def rot_m(theta, phi, vertex):
    x, y, z = vertex
    st, ct = math.sin(theta), math.cos(theta)
    sp, cp = math.sin(phi), math.cos(phi)
    return (-st * x + ct * y,
            -ct * cp * x - st * cp * y + sp * z)


def rot_r(alpha, point):
    x, y = point
    s, c = math.sin(alpha), math.cos(alpha)
    return (c * x - s * y, s * x + c * y)


def cross(left, right):
    return left[0] * right[1] - left[1] * right[0]


def dot(left, right):
    return left[0] * right[0] + left[1] * right[1]


def dot3(left, right):
    return sum(x * y for x, y in zip(left, right))


def cross3(left, right):
    return (left[1] * right[2] - left[2] * right[1],
            left[2] * right[0] - left[0] * right[2],
            left[0] * right[1] - left[1] * right[0])


def add3(*vectors):
    return tuple(sum(vector[i] for vector in vectors) for i in range(3))


def scale3(scale, vector):
    return tuple(scale * value for value in vector)


def norm3(vector):
    return math.sqrt(dot3(vector, vector))


def outer_lift(theta, phi, direction):
    """Adjoint of ``rot_m``: lift a screen direction to world space."""
    u, v = direction
    st, ct = math.sin(theta), math.cos(theta)
    sp, cp = math.sin(phi), math.cos(phi)
    return (-st * u - ct * cp * v,
            ct * u - st * cp * v,
            sp * v)


def solve_linear(matrix, rhs):
    """Small dense Gaussian elimination, returning None if singular."""
    augmented = [list(row) + [value] for row, value in zip(matrix, rhs)]
    size = len(rhs)
    for column in range(size):
        pivot = max(range(column, size),
                    key=lambda row: abs(augmented[row][column]))
        if abs(augmented[pivot][column]) < 1e-12:
            return None
        augmented[column], augmented[pivot] = augmented[pivot], augmented[column]
        divisor = augmented[column][column]
        augmented[column] = [value / divisor
                             for value in augmented[column]]
        for row in range(size):
            if row == column:
                continue
            multiplier = augmented[row][column]
            augmented[row] = [left - multiplier * right for left, right in
                              zip(augmented[row], augmented[column])]
    return [augmented[row][-1] for row in range(size)]


def tetrahedron_origin_margin(points):
    """Radius of the origin-centered ball in a tetrahedron, or None."""
    matrix = [[points[column][row] for column in range(4)]
              for row in range(3)] + [[1.0] * 4]
    barycentric = solve_linear(matrix, [0.0, 0.0, 0.0, 1.0])
    if barycentric is None or min(barycentric) <= 1e-10:
        return None
    face_distances = []
    for omitted in range(4):
        face = [points[i] for i in range(4) if i != omitted]
        ab = tuple(face[1][i] - face[0][i] for i in range(3))
        ac = tuple(face[2][i] - face[0][i] for i in range(3))
        normal = cross3(ab, ac)
        length = norm3(normal)
        if length < 1e-12:
            return None
        face_distances.append(abs(dot3(normal, face[0])) / length)
    return min(face_distances), barycentric


def rational_unit_direction(direction, denominator=10**6):
    """Nearby exact rational point on the unit circle."""
    x, y = direction
    if x > -0.5:
        tangent = y / (1.0 + x)
        p, q = round(tangent * denominator), denominator
        divisor = q * q + p * p
        return (Q(q * q - p * p, divisor), Q(2 * p * q, divisor))
    # Cotangent chart avoids an enormous half-angle parameter near (-1, 0).
    cotangent = (1.0 + x) / y
    p, q = round(cotangent * denominator), denominator
    divisor = q * q + p * p
    return (Q(p * p - q * q, divisor), Q(2 * p * q, divisor))


def rationalized_certificate(pose, denominator=10**6):
    certificate = balanced_certificate(tuple(map(float, pose)))
    directions = [rational_unit_direction(row["normal"], denominator)
                  for row in certificate["contacts"]]
    weights = [cross(directions[1], directions[2]),
               cross(directions[2], directions[0]),
               cross(directions[0], directions[1])]
    if all(weight <= 0 for weight in weights):
        weights = [-weight for weight in weights]
    if not all(weight >= 0 for weight in weights):
        raise RuntimeError("rationalization destroyed positive balance")
    return {
        "pose": list(pose),
        "contacts": [{
            "inner": row["inner"],
            "outer": row["outer_start"],
            "direction": list(direction),
            "weight": weight,
        } for row, direction, weight in
            zip(certificate["contacts"], directions, weights)],
    }


def convex_hull(points):
    """Indices of the counterclockwise strict convex hull."""
    ordered = sorted(range(len(points)), key=lambda i: points[i])

    def half(indices):
        answer = []
        for index in indices:
            while len(answer) >= 2:
                a, b = points[answer[-2]], points[answer[-1]]
                ab = (b[0] - a[0], b[1] - a[1])
                bp = (points[index][0] - b[0], points[index][1] - b[1])
                if cross(ab, bp) > 1e-14:
                    break
                answer.pop()
            answer.append(index)
        return answer

    lower = half(ordered)
    upper = half(reversed(ordered))
    return lower[:-1] + upper[:-1]


def balanced_certificate(pose):
    theta1, phi1, theta2, phi2, alpha = pose
    inner = [rot_r(alpha, rot_m(theta1, phi1, vertex))
             for vertex in VERTICES]
    outer = [rot_m(theta2, phi2, vertex) for vertex in VERTICES]
    cycle = convex_hull(outer)
    contacts = []
    for position, start in enumerate(cycle):
        finish = cycle[(position + 1) % len(cycle)]
        edge = (outer[finish][0] - outer[start][0],
                outer[finish][1] - outer[start][1])
        norm = math.hypot(*edge)
        normal = (edge[1] / norm, -edge[0] / norm)
        outer_support = dot(normal, outer[start])
        inner_index = max(range(len(inner)),
                          key=lambda i: dot(normal, inner[i]))
        displacement = dot(normal, inner[inner_index]) - outer_support
        contacts.append((normal, displacement, inner_index, start, finish))

    best = None
    for indices in itertools.combinations(range(len(contacts)), 3):
        normals = [contacts[i][0] for i in indices]
        weights = [cross(normals[1], normals[2]),
                   cross(normals[2], normals[0]),
                   cross(normals[0], normals[1])]
        if all(weight <= 1e-14 for weight in weights):
            weights = [-weight for weight in weights]
        if not all(weight >= -1e-14 for weight in weights):
            continue
        total = sum(weights)
        if total <= 1e-14:
            continue
        weights = [max(weight, 0.0) / total for weight in weights]
        obstruction = sum(weights[j] * contacts[index][1]
                          for j, index in enumerate(indices))
        if best is None or obstruction > best[0]:
            best = (obstruction, indices, weights)

    if best is None:
        raise RuntimeError("outer silhouette has no balanced edge triple")
    obstruction, indices, weights = best
    return {
        "obstruction": obstruction,
        "outer_hull_size": len(cycle),
        "weights": weights,
        "contacts": [{
            "normal": contacts[index][0],
            "inner": contacts[index][2],
            "outer_start": contacts[index][3],
            "outer_finish": contacts[index][4],
            "displacement": contacts[index][1],
        } for index in indices],
    }


def local_axis_candidates(theta, phi, cone_samples=1):
    """Balanced equality-stratum triples for one outer viewing direction.

    Directions are chosen strictly inside silhouette-vertex normal cones.
    Each result stores the normalized first-variation vector A/B used by the
    axis-free local theorem and its smallest (floating-point) support slack.
    """
    outer = [rot_m(theta, phi, vertex) for vertex in VERTICES]
    cycle = convex_hull(outer)
    edge_normals = []
    for position, start in enumerate(cycle):
        finish = cycle[(position + 1) % len(cycle)]
        edge = (outer[finish][0] - outer[start][0],
                outer[finish][1] - outer[start][1])
        length = math.hypot(*edge)
        edge_normals.append((edge[1] / length, -edge[0] / length))

    contacts = []
    for position, vertex_index in enumerate(cycle):
        before = edge_normals[(position - 1) % len(cycle)]
        after = edge_normals[position]
        angle_before = math.atan2(before[1], before[0])
        angle_after = math.atan2(after[1], after[0])
        while angle_after <= angle_before:
            angle_after += 2.0 * math.pi
        for sample in range(cone_samples):
            fraction = (sample + 1) / (cone_samples + 1)
            angle = angle_before + fraction * (angle_after - angle_before)
            direction = (math.cos(angle), math.sin(angle))
            support = dot(direction, outer[vertex_index])
            slack = min(support - dot(direction, outer[other])
                        for other in range(len(outer))
                        if other != vertex_index)
            contacts.append({
                "vertex": vertex_index,
                "direction": direction,
                "support_slack": slack,
            })

    candidates = []
    for contact_indices in itertools.combinations(range(len(contacts)), 3):
        selected = [contacts[index] for index in contact_indices]
        directions = [contact["direction"] for contact in selected]
        weights = [cross(directions[1], directions[2]),
                   cross(directions[2], directions[0]),
                   cross(directions[0], directions[1])]
        if all(weight <= 1e-12 for weight in weights):
            weights = [-weight for weight in weights]
        if not all(weight > 1e-10 for weight in weights):
            continue
        total = sum(weights)
        weights = [weight / total for weight in weights]
        terms = []
        for weight, contact in zip(weights, selected):
            lift = outer_lift(theta, phi, contact["direction"])
            terms.append(scale3(
                weight, cross3(VERTICES[contact["vertex"]], lift)))
        normalized_a = add3(*terms)  # B = sum weights = 1.
        candidates.append({
            "contacts": selected,
            "weights": weights,
            "normalized_a": normalized_a,
            "support_slack": min(contact["support_slack"]
                                 for contact in selected),
        })
    return cycle, candidates


def best_local_tetrahedron(theta, phi, cone_samples=1,
                           max_tetrahedra=100_000):
    cycle, candidates = local_axis_candidates(theta, phi, cone_samples)
    best = None
    total_tetrahedra = math.comb(len(candidates), 4)
    if total_tetrahedra <= max_tetrahedra:
        tetrahedra = itertools.combinations(range(len(candidates)), 4)
        searched_tetrahedra = total_tetrahedra
    else:
        # Discovery only: a deterministic broad sample is enough to measure
        # whether healthy tetrahedra exist.  A selected certificate is later
        # rationalized and checked exhaustively by Lean.
        rng = random.Random(repr((theta, phi, cone_samples)))
        sampled = set()
        while len(sampled) < max_tetrahedra:
            sampled.add(tuple(sorted(rng.sample(range(len(candidates)), 4))))
        tetrahedra = sampled
        searched_tetrahedra = len(sampled)
    for indices in tetrahedra:
        points = [candidates[index]["normalized_a"] for index in indices]
        result = tetrahedron_origin_margin(points)
        if result is None:
            continue
        margin, barycentric = result
        support_slack = min(candidates[index]["support_slack"]
                            for index in indices)
        score = min(margin, support_slack)
        key = (score, margin, support_slack)
        if best is None or key > best[0]:
            best = (key, indices, barycentric)
    if best is None:
        return {
            "theta": theta,
            "phi": phi,
            "outer_hull": cycle,
            "candidate_count": len(candidates),
            "total_tetrahedra": total_tetrahedra,
            "searched_tetrahedra": searched_tetrahedra,
            "found": False,
        }
    (score, margin, support_slack), indices, barycentric = best
    return {
        "theta": theta,
        "phi": phi,
        "outer_hull": cycle,
        "candidate_count": len(candidates),
        "total_tetrahedra": total_tetrahedra,
        "searched_tetrahedra": searched_tetrahedra,
        "found": True,
        "score": score,
        "axis_ball_radius": margin,
        "support_slack": support_slack,
        "origin_barycentric": barycentric,
        "certificates": [candidates[index] for index in indices],
    }


def local_random_profile(samples, seed, cone_samples=1):
    rng = random.Random(seed)
    minimum = None
    failures = 0
    for _ in range(samples):
        theta = rng.uniform(-math.pi, math.pi)
        phi = rng.uniform(0.0, math.pi)
        result = best_local_tetrahedron(theta, phi, cone_samples)
        if not result["found"]:
            failures += 1
            continue
        if minimum is None or result["score"] < minimum["score"]:
            minimum = result
    return {
        "samples": samples,
        "failures": failures,
        "minimum": minimum,
    }


def rational_local_zero_certificate(denominator=10_000):
    """Rationalize the four-certificate local witness at outer view (0, 0)."""
    result = best_local_tetrahedron(0.0, 0.0)
    if not result["found"]:
        raise RuntimeError("no local tetrahedron at the zero outer view")
    certificates = []
    for certificate in result["certificates"]:
        directions = [rational_unit_direction(
            contact["direction"], denominator)
            for contact in certificate["contacts"]]
        weights = [cross(directions[1], directions[2]),
                   cross(directions[2], directions[0]),
                   cross(directions[0], directions[1])]
        if all(weight < 0 for weight in weights):
            weights = [-weight for weight in weights]
        if not all(weight > 0 for weight in weights):
            raise RuntimeError("local rationalization lost positive balance")
        total = sum(weights)
        a = [Q(0), Q(0), Q(0)]
        support_slacks = []
        contacts = []
        for weight, direction, old_contact in zip(
                weights, directions, certificate["contacts"]):
            vertex_index = old_contact["vertex"]
            x, y, z = VERTICES_Q[vertex_index]
            u, v = direction
            term = (-z * u, -z * v, x * u + y * v)
            a = [value + weight * coordinate
                 for value, coordinate in zip(a, term)]
            projected = [(other[1], -other[0]) for other in VERTICES_Q]
            support = dot(direction, projected[vertex_index])
            slack = min(support - dot(direction, projected[other])
                        for other in range(len(projected))
                        if other != vertex_index)
            support_slacks.append(slack)
            contacts.append({
                "vertex": vertex_index,
                "direction": list(direction),
            })
        certificates.append({
            "contacts": contacts,
            "weights": weights,
            "B": total,
            "A": a,
            "normalized_A": [coordinate / total for coordinate in a],
            "support_slack": min(support_slacks),
        })
    return {
        "center": [Q(0), Q(0)],
        "suggested_c": Q(1, 100),
        "certificates": certificates,
    }


def random_profile(samples, seed):
    rng = random.Random(seed)
    minimum = None
    negative = 0
    hull_histogram = {}
    for _ in range(samples):
        pose = (rng.uniform(-math.pi, math.pi),
                rng.uniform(0.0, math.pi),
                rng.uniform(-math.pi, math.pi),
                rng.uniform(0.0, math.pi),
                rng.uniform(-math.pi, math.pi))
        certificate = balanced_certificate(pose)
        hull_size = certificate["outer_hull_size"]
        hull_histogram[hull_size] = hull_histogram.get(hull_size, 0) + 1
        if certificate["obstruction"] < 0:
            negative += 1
        if minimum is None or certificate["obstruction"] < minimum[0]:
            minimum = (certificate["obstruction"], pose, certificate)
    return {
        "samples": samples,
        "negative_obstructions": negative,
        "minimum_obstruction": minimum[0],
        "minimum_pose": minimum[1],
        "minimum_certificate": minimum[2],
        "outer_hull_histogram": hull_histogram,
    }


def main():
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="command", required=True)
    profile = sub.add_parser("profile")
    profile.add_argument("--samples", type=int, default=10000)
    profile.add_argument("--seed", type=int, default=1)
    pose = sub.add_parser("pose")
    pose.add_argument("values", help="theta1,phi1,theta2,phi2,alpha")
    audit = sub.add_parser("audit-stl")
    audit.add_argument("path")
    rational = sub.add_parser("rational-certificate")
    rational.add_argument("values", help="theta1,phi1,theta2,phi2,alpha")
    rational.add_argument("--denominator", type=int, default=10**6)
    local = sub.add_parser("local-view")
    local.add_argument("values", help="theta2,phi2")
    local.add_argument("--cone-samples", type=int, default=1)
    local_profile = sub.add_parser("local-profile")
    local_profile.add_argument("--samples", type=int, default=100)
    local_profile.add_argument("--seed", type=int, default=1)
    local_profile.add_argument("--cone-samples", type=int, default=1)
    local_zero = sub.add_parser("local-rational-zero")
    local_zero.add_argument("--denominator", type=int, default=10_000)
    args = parser.parse_args()
    if args.command == "profile":
        print(json.dumps(random_profile(args.samples, args.seed), indent=2))
    elif args.command == "pose":
        values = tuple(map(float, args.values.split(",")))
        if len(values) != 5:
            parser.error("pose requires five comma-separated values")
        print(json.dumps(balanced_certificate(values), indent=2))
    elif args.command == "audit-stl":
        print(json.dumps(audit_stl(args.path), indent=2))
    elif args.command == "local-view":
        values = tuple(map(float, args.values.split(",")))
        if len(values) != 2:
            parser.error("local-view requires theta2,phi2")
        print(json.dumps(best_local_tetrahedron(
            *values, args.cone_samples), indent=2))
    elif args.command == "local-profile":
        print(json.dumps(local_random_profile(
            args.samples, args.seed, args.cone_samples), indent=2))
    elif args.command == "local-rational-zero":
        print(json.dumps(rational_local_zero_certificate(
            args.denominator), indent=2, default=str))
    else:
        values = tuple(Q(value) for value in args.values.split(","))
        if len(values) != 5:
            parser.error("pose requires five comma-separated values")
        result = rationalized_certificate(values, args.denominator)
        print(json.dumps(result, indent=2, default=str))


if __name__ == "__main__":
    main()
